Better test for iconv

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3327,9 +3327,13 @@ done
 # some special libs need to be set for package.conf files
 if echo "$LIBS" | grep iconv > /dev/null 2>&1 ; then
     ICONV=iconv
-else
-    :
-# AC_MSG_ERROR(You need libiconv to run Yi)
+fi
+
+# it is fatal
+if test "x$ac_cv_lib_iconv_libiconv" = "xno"; then
+        { { echo "$as_me:$LINENO: error: You need libiconv to run Yi" >&5
+echo "$as_me: error: You need libiconv to run Yi" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 if (echo "$LIBS" | grep ncursesw) >/dev/null 2>&1 ; then
