Make the absence of libiconv a fatal configure error

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3319,17 +3319,18 @@ done
 
 
 # On linux we need to call doupdate() after endwin() to restore the term
-if uname -s | grep Linux > /dev/null 2>&1 ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define NCURSES_UPDATE_AFTER_END 1
-_ACEOF
-
-fi
+#if uname -s | grep Linux > /dev/null 2>&1 ; then
+#    AC_DEFINE( [NCURSES_UPDATE_AFTER_END],[1],
+#               [Define to 1 if you need to call doupdate after endwin])
+#fi
 
 # some special libs need to be set for package.conf files
 if echo "$LIBS" | grep iconv > /dev/null 2>&1 ; then
     ICONV=iconv
+else
+    { { echo "$as_me:$LINENO: error: You need libiconv to run Yi" >&5
+echo "$as_me: error: You need libiconv to run Yi" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 if (echo "$LIBS" | grep ncursesw) >/dev/null 2>&1 ; then
